# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/DEV/powerReconf/vivado/soc_proj.runs/synth_1/bd_soc_proj_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/David/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12420-FREISMUTHDESK/incrSyn
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/DEV/powerReconf/vivado/soc_proj.cache/wt [current_project]
set_property parent.project_path D:/DEV/powerReconf/vivado/soc_proj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {D:/Xilinx/BoardStore/XilinxBoardStore-2020.1} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  d:/DEV/powerReconf/vivado/ip_repo/experiment_axi_wrapper_1.0
  d:/DEV/powerReconf/experiment_axi/experiment_axi_1.0
  d:/DEV/powerReconf/ip_repo/myip_1.0
  d:/DEV/powerReconf/ip_repo/myip_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/DEV/powerReconf/vivado/soc_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/David/vitis/mb_test_app_2/Debug/mb_test_app_2.elf
set_property SCOPED_TO_REF bd_soc_proj [get_files -all C:/Users/David/vitis/mb_test_app_2/Debug/mb_test_app_2.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all C:/Users/David/vitis/mb_test_app_2/Debug/mb_test_app_2.elf]
read_verilog -library xil_defaultlib D:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/hdl/bd_soc_proj_wrapper.v
add_files D:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/bd_soc_proj.bd
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_0/bd_soc_proj_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_0/bd_soc_proj_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_0/bd_soc_proj_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_dlmb_v10_0/bd_soc_proj_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_ilmb_v10_0/bd_soc_proj_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_dlmb_bram_if_cntlr_0/bd_soc_proj_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_ilmb_bram_if_cntlr_0/bd_soc_proj_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_lmb_bram_0/bd_soc_proj_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_mdm_1_0/bd_soc_proj_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_mdm_1_0/bd_soc_proj_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_clk_wiz_1_0/bd_soc_proj_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_clk_wiz_1_0/bd_soc_proj_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_clk_wiz_1_0/bd_soc_proj_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_rst_clk_wiz_1_100M_0/bd_soc_proj_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_rst_clk_wiz_1_100M_0/bd_soc_proj_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_rst_clk_wiz_1_100M_0/bd_soc_proj_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_quad_spi_0_0/bd_soc_proj_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_quad_spi_0_0/bd_soc_proj_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_quad_spi_0_0/bd_soc_proj_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_quad_spi_0_0/bd_soc_proj_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_uartlite_0_0/bd_soc_proj_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_uartlite_0_0/bd_soc_proj_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_uartlite_0_0/bd_soc_proj_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_xbar_0/bd_soc_proj_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_hwicap_0_0/bd_soc_proj_axi_hwicap_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_hwicap_0_0/bd_soc_proj_axi_hwicap_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_hwicap_0_0/bd_soc_proj_axi_hwicap_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_gpio_0_0/bd_soc_proj_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_gpio_0_0/bd_soc_proj_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_axi_gpio_0_0/bd_soc_proj_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_xadc_wiz_0_0/bd_soc_proj_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_xadc_wiz_0_0/bd_soc_proj_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_auto_pc_0/bd_soc_proj_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/bd_soc_proj_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/DEV/powerReconf/vivado/soc_proj.srcs/sources_1/bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/DEV/powerReconf/constraints/pinning.xdc
set_property used_in_implementation false [get_files D:/DEV/powerReconf/constraints/pinning.xdc]

read_xdc D:/DEV/powerReconf/constraints/contraints.xdc
set_property used_in_implementation false [get_files D:/DEV/powerReconf/constraints/contraints.xdc]

read_xdc D:/DEV/powerReconf/constraints/pblocks.xdc
set_property used_in_implementation false [get_files D:/DEV/powerReconf/constraints/pblocks.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bd_soc_proj_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_soc_proj_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bd_soc_proj_wrapper_utilization_synth.rpt -pb bd_soc_proj_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
