# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/DEV/powerReconf/constraints/pinning.xdc

# XDC: D:/DEV/powerReconf/constraints/contraints.xdc

# XDC: D:/DEV/powerReconf/constraints/pblocks.xdc

# Block Designs: bd/bd_soc_proj/bd_soc_proj.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj || ORIG_REF_NAME==bd_soc_proj} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_0/bd_soc_proj_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_microblaze_0_0 || ORIG_REF_NAME==bd_soc_proj_microblaze_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_dlmb_v10_0/bd_soc_proj_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_dlmb_v10_0 || ORIG_REF_NAME==bd_soc_proj_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_ilmb_v10_0/bd_soc_proj_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_ilmb_v10_0 || ORIG_REF_NAME==bd_soc_proj_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_dlmb_bram_if_cntlr_0/bd_soc_proj_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_soc_proj_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_ilmb_bram_if_cntlr_0/bd_soc_proj_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_soc_proj_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_lmb_bram_0/bd_soc_proj_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_lmb_bram_0 || ORIG_REF_NAME==bd_soc_proj_lmb_bram_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_mdm_1_0/bd_soc_proj_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_mdm_1_0 || ORIG_REF_NAME==bd_soc_proj_mdm_1_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_clk_wiz_1_0/bd_soc_proj_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_clk_wiz_1_0 || ORIG_REF_NAME==bd_soc_proj_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_rst_clk_wiz_1_100M_0/bd_soc_proj_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_soc_proj_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_axi_quad_spi_0_0/bd_soc_proj_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_axi_quad_spi_0_0 || ORIG_REF_NAME==bd_soc_proj_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_axi_uartlite_0_0/bd_soc_proj_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_axi_uartlite_0_0 || ORIG_REF_NAME==bd_soc_proj_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_xbar_0/bd_soc_proj_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_xbar_0 || ORIG_REF_NAME==bd_soc_proj_xbar_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_microblaze_0_axi_periph_0/bd_soc_proj_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bd_soc_proj_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_reset_inv_0_0/bd_soc_proj_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_reset_inv_0_0 || ORIG_REF_NAME==bd_soc_proj_reset_inv_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_axi_hwicap_0_0/bd_soc_proj_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_axi_hwicap_0_0 || ORIG_REF_NAME==bd_soc_proj_axi_hwicap_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_ExperimentSystem_0_0/bd_soc_proj_ExperimentSystem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_ExperimentSystem_0_0 || ORIG_REF_NAME==bd_soc_proj_ExperimentSystem_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_axi_gpio_0_0/bd_soc_proj_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_axi_gpio_0_0 || ORIG_REF_NAME==bd_soc_proj_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_xlconstant_0_0/bd_soc_proj_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_xlconstant_0_0 || ORIG_REF_NAME==bd_soc_proj_xlconstant_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_xadc_wiz_0_0/bd_soc_proj_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_xadc_wiz_0_0 || ORIG_REF_NAME==bd_soc_proj_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/bd_soc_proj/ip/bd_soc_proj_auto_pc_0/bd_soc_proj_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_soc_proj_auto_pc_0 || ORIG_REF_NAME==bd_soc_proj_auto_pc_0} -quiet] -quiet

# XDC: bd/bd_soc_proj/bd_soc_proj_ooc.xdc
