####Budget constraints for cell bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule####
#Input pins:
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][0]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][0]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][0]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__0_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][1]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][1]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][1]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__1_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][2]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][2]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][2]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__2_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][3]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][3]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][3]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__3_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][4]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][4]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][4]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__4_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][5]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][5]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][5]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__5_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][6]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][6]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][6]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__6_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][7]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][7]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][7]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__7_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][8]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][8]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][8]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__8_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][9]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][9]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][9]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__9_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][10]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][10]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][10]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__10_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][11]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][11]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][11]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__11_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][12]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][12]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][12]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__12_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][13]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][13]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][13]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__13_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][14]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][14]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][14]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__14_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Xin][15]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][15]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/A_reg[0][15]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Xin__15_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][0]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][0]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][0]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__0_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][1]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][1]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][1]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__1_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][2]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][2]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][2]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__2_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][3]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][3]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][3]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__3_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][4]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][4]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][4]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__4_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][5]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][5]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][5]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__5_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][6]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][6]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][6]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__6_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][7]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][7]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][7]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__7_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][8]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][8]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][8]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__8_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][9]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][9]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][9]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__9_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][10]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][10]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][10]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__10_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][11]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][11]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][11]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__11_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][12]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][12]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][12]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__12_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][13]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][13]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][13]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__13_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][14]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][14]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][14]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__14_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleInputs[Yin][15]	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][15]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/B_reg[0][15]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_moduleInputs_Yin__15_/I0] 5.0
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/triggerMeasurement	Logic Levels: 1	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.5
set_max_delay -datapath_only -from [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/triggerMeasurement_reg[0]_C/C} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/triggerMeasurement_reg[0]_P/C}]] -to [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_IN_BUF_triggerMeasurement/I0] 5.0

#Output pins:
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_0_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[0]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_0_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_1_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[1]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_1_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[1]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[1]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_2_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[2]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_2_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[2]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[2]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_3_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[3]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_3_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[3]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[3]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_4_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[4]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_4_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[4]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[4]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_5_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[5]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_5_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[5]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[5]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_6_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[6]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_6_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[6]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[6]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_7_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[7]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_7_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[7]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[7]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_8_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[8]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_8_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[8]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[8]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_9_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[9]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_9_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[9]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[9]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_10_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[10]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_10_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[10]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[10]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_11_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[11]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_11_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[11]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[11]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_12_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[12]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_12_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[12]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[12]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_13_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[13]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_13_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[13]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[13]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_14_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[14]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_14_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[14]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[14]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_15_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[15]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_15_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[15]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[15]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_16_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[16]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_16_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[16]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[16]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_17_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[17]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_17_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[17]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[17]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_18_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[18]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_18_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[18]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[18]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_19_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[19]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_19_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[19]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[19]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_20_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[20]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_20_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[20]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[20]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_21_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[21]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_21_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[21]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[21]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_22_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[22]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_22_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[22]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[22]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_23_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[23]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_23_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[23]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[23]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_24_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[24]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_24_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[24]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[24]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_25_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[25]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_25_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[25]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[25]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_26_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[26]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_26_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[26]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[26]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_27_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[27]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_27_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[27]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[27]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_28_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[28]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_28_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[28]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[28]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_29_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[29]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_29_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[29]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[29]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_30_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[30]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_30_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[30]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[30]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_31_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/agingSensorValue[31]	Logic Levels: 3	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.7
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_agingSensorValue_31_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[31]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[31]_P/PRE}]] 7.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__0_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][0]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__0_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__1_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][1]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__1_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[1]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[1]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__2_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][2]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__2_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[2]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[2]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__3_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][3]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__3_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[3]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[3]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__4_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][4]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__4_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[4]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[4]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__5_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][5]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__5_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[5]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[5]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__6_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][6]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__6_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[6]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[6]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__7_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][7]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__7_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[7]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[7]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__8_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][8]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__8_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[8]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[8]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__9_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][9]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__9_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[9]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[9]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__10_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][10]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__10_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[10]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[10]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__11_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][11]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__11_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[11]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[11]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__12_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][12]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__12_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[12]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[12]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__13_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][13]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__13_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[13]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[13]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__14_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][14]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__14_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[14]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[14]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__15_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][15]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__15_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[15]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[15]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__16_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][16]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__16_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[16]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[16]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__17_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][17]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__17_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[17]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[17]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__18_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][18]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__18_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[18]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[18]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__19_/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/moduleOutputs[Aout][19]	Logic Levels: 4	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_moduleOutputs_Aout__19_/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[19]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[19]_P/PRE}]] 8.0
set_logic_dc [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_ready/I0]
#Pin: bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/ready	Logic Levels: 5	Clock: clk_out1_bd_soc_proj_clk_wiz_1_0	Period: 10.000	Budget: 0.8
set_max_delay -datapath_only -from [get_pins bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experiment/reconfigurableModules[0].reconfigurableModuleFrame/ReconfigurableModule[1].reconfigureableModule/HD_PR_Connection_S_OUT_BUF_ready/O] -to [get_pins [list {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_C/CLR} {bd_soc_proj_i/ExperimentSystem_0/inst/experimentWrapper/experimentDataMux/data_out_reg[0]_P/PRE}]] 8.0
